### ISSUE TITLE
Error in glm.fit: NA/NaN/Inf in 'x'

### ISSUE THREAD

**Issue by paulstaab** [statgenlmu/jaatha#7] opened 2014-06-30 13:02 UTC
In 2.4-1 the following error might occur during initial seach when using smoothing:

```
Error in glm.fit(x = c(1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,  : NA/NaN/Inf in 'x'
```

Might be related to the new parameter parsing.

**Comment by caoyin916** [comment] 2016-06-07 14:20
Dear paulstaab, I recently ran into the same error message when I try to run glm tweedie model. Do you have any solutions? Thanks!

**Comment by SaleemPak** [comment] 2017-10-26 07:24
Hi

I am also ocassionally facing following error message when i am trying to fit glm gamma model using log link function to simulate precipitation using set of predictor variables. I am bootstrapong 1000 times from available time series and computing fit of model statistics for each sample. However, ocassionaly i face this problem.

Error in glm.fit(x = c(1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,  : 
  NA/NaN/Inf in 'x'

I tried to read from web about this issue (it has been reported many times), however its understanding is far above my head. 

anybody can help?

I shall be grateful

**Comment by paulstaab** [comment] 2017-10-26 08:06
I'll look into it.

**Comment by SaleemPak** [comment] 2017-10-26 08:12
Thanks Paul

Thanks alot.

my working code is below
# Now take bootsraping sampling
set.seed(123)
ns = 1000  ## no of random samples

samps = vector(ns, mode = "list")  ## set a variable of type list to store
random samples.

for (i in 1:ns) {

  samps [[i]] = sample.int(prci_length, size = (2*prci_length/3))   ## 2/3
of data as calibration data set
}




## define x and y vectors for GLM applications by using random sample
indicies developed above
glm_model = vector(ns, mode = "list") ## define a variable outside loop for
storing glm results
glm_summary = vector(ns, mode = "list") ## defining empy list for storing
glmsummary results
##mse0 = vector(ns, mode = "list") ## variable for storing MSEs of each glm
mode
mse_1 = vector(ns, mode = "list") ## variable for storing revised MSEs of
each model
mse_2 = vector(ns, mode = "list")
in_pre = vector(ns, mode = "list")
BPred = vector(ns, mode = "list")
mse_0 = matrix(nrow = ns, ncol = 4)
##mse1 = vector(ns, mode = "length")
mse_3 = vector(ns, mode = "list")
y_Cal = vector(ns, mode = "list")
y_Val = vector(ns, mode = "list")
Modeled_Cal = vector(ns, mode = "list")
modeled_val = vector (ns, mode = "list")
mse_BM = matrix(nrow = ns, ncol = 3)
MSESS_Cal = vector(length = ns)
MSESS_Val= vector(length = ns)
for (i in 1:ns) {{


  x = pred[samps[[i]],-1]
  x##avg_Cal[[i]] = x
  y = prci[samps[[i]],-1]
  y_Cal[[i]] = y
  xval = pred[-(samps[[i]]),-1]
  ##avg_Val[[i]] = xval
  yval = prci[-(samps[[i]]), -1]
  y_Val[[i]] = yval

 x1 = x[1:6]  ## subset of predictors against which corelation is required

  y1 = x[7:length(x)]


  corresult = cor(x=x1,y=y1, method = "spearman") ## aplly pearson
corelation function on predictor data.set

  corresult1 = which(abs(corresult) > 0.50, arr.ind = T)
   if (length(corresult1) == 0 ) {corresult1 = y1
   info = corresult1
   newpredictor = y1
   x = data.frame(x1, newpredictor)
  ## avg_Cal[[i]] = x

   xval = xval[colnames(x)]}

  ## avg_Val[[i]]= xval}
  else { corresult1 = corresult1
  info = unique(corresult1[,2])
  newpredictor = y1[-(info)]
   x = data.frame(x1, newpredictor)



  mse_in = matrix(nrow = length(x) , ncol = 4)
  for(j in 1:length(x)) { ## depends upon No of predictors in analysis.
    xsel = x[,-j]
   ## avg_Cal[[i]] = xsel
    xsel_val = xval[,-j]
   ## avg_Val[[i]] = xsel_val
    ##glm_model[[i]] = glm(y ~., data = xsel, family = "quasi"(link =
"log", variance = "mu^2"))
    glm_model[[i]] = glm(y~., data = xsel, family= Gamma(link = "log"),
maxit = 1000)
    glm_summary[[i]] = summary(glm_model[[i]])

    m_pred = predict(glm_model[[i]], type = "response")
    Modeled_Cal[[i]] = m_pred

    m_valpre = predict(glm_model[[i]], newdata = xsel_val, type =
"response")

    modeled_val[[i]] = m_valpre
    mse_in[j,1] = sum((m_pred- y)^2)/length(y)
    mse_in[j,2] = sum((m_valpre - yval)^2)/length(yval)
    mse_in[j,3] = mse_in[j,1] + mse_in[j,2]
  }
  mse_in[,4] = rank(-mse_in[,3])

  mse_1[[i]] = mse_in

  ## }

  ## predictor identification process, which of x is rated at what level.

  #id_pred = vector(length = length(x))

  ##for (m in 1: length(x)) {

  ##  predictor = which(mse_in[,4]== m)

  ## id_pred[m] = predictor

  ##}



  mse_fin = matrix(nrow = length(x) -1, ncol =4)

  for(k in 2:length(x)) {

    kk = k-1
    final = which(mse_in[,4] <= k)
    xfinal = x[,final]

   ## avg_Cal[[i]] = xfinal
    xval_final = xval[, final]

   ## avg_Val[[i]] = xval_final
    ##glm_model[[i]] = glm(y ~., data = xfinal, family = "quasi"(link =
"log", variance = "mu^2"))
    glm_model[[i]] = glm(y~., data = xfinal, family = Gamma(link =
"log"),maxit = 1000)
    glm_summary[[i]] = summary(glm_model[[i]])
    m_pred = predict(glm_model[[i]], type = "response")
    Modeled_Cal[[i]] = m_pred
    m_valpre = predict(glm_model[[i]], newdata = xval_final, type =
"response")
    modeled_val[[i]] = m_valpre
    mse_fin[kk,1] = sum((m_pred - y) **2)/length(y)
    mse_fin[kk,2] = sum((m_valpre - yval) **2)/length(yval)
    mse_fin[kk,3] = mse_fin[kk,1] + mse_fin[kk,2]
  }

  mse_fin[,4] = rank(mse_fin[,3])

  mse_3[[i]] = mse_fin

  ##}
  ## identifying right no of predictors from final model(s)

  opt = which.min(mse_fin[,4])
  opt = opt +1

  opt1 =which(mse_in[,4] <=opt )

  opt2 = x[,opt1]
  ##best_pred[[i]] = colnames(opt2)
  BPred[[i]] = colnames(opt2)
##}
  ## using final model (with least sum of MSEs) for final computations
  ##mse_BM = matrix(nrow = i, ncol = 3)
  xfinal = opt2
  xval_final = xval[colnames(opt2)]

  glm_model[[i]] = glm(y~., data = xfinal, family = Gamma(link =
"log"),maxit =1000)
  glm_summary[[i]] = summary(glm_model[[i]])
  m_pred = predict(glm_model[[i]], type = "response")
  Modeled_Cal[[i]] = m_pred
  m_valpre = predict(glm_model[[i]], newdata = xval_final, type =
"response")
  modeled_val[[i]] = m_valpre
  mse_BM[i,1] =  sum((m_pred - y) **2)/length(y)
  mse_BM[i,2] = sum((m_valpre - yval) **2)/length(yval)
  mse_BM[i,3] = mse_BM[i,1] + mse_BM[i,2]
  cli_Cal_Avg_error = sum((mean(y) - y)**2)/length(y)
  cli_Val_Avg_error = sum((mean(yval) - yval)**2)/length(yval)
  MSESS_Cal[i] = (1 - mse_BM[i,1]/cli_Cal_Avg_error)*100
  MSESS_Val[i] = (1 - mse_BM[i,2]/cli_Val_Avg_error)*100
 ## mse_BM1[[i]] = mse_BM
}## closing of loop

thanks for in anticipation

with best regards

Saleem







*Keep Faith and SmilingMalik Muhammad Saleem*






*PhD Research ScholarFaculty of Applied Computer ScienceInstitute of
GeographyDepartment of Physical Geography and Quantitative
MethodsUniversity *


*of Augsburg 86159Germany.*

*Phone (Cell)  : +49-15217256385*

*Phone (Off)    : +49-821 598 2712*

*Fax (Off)         : +49- 821 598-2264*

*Phone (Home): +49- 8231 9786967*

**Comment by smirnovayu** [comment] 2018-06-13 09:20
In my case the problem was in the data.
 I have log-transformed on of the right-skewed variables and when I used it, log-regression resulted in this error. When I used the original (untransformed) variant - it worked perfect.

**Comment by paulstaab** [comment] 2018-06-17 13:20
Great that you were able to solve your problem - tracking this one down is pretty tricky.

**Comment by rxyang** [comment] 2019-03-06 23:54
@smirnovayu Very likely your log-transformed variable contains 0's. It's customary to add 1 to the variable before transformation, i.e log(X+1).

**Comment by Verasok11** [comment] 2019-05-15 13:16
Hi, I am getting the same error when running tweedieReserve function on a triangle of loss data (tweedieReserve uses glm.git). Was there a solution to this issue?

**Comment by Shicheng-Guo** [comment] 2019-05-29 16:36
1. first check missing values: NA/NAN/Inf
2. second check sd(x), remove variables whose sd=0

**Comment by irital** [comment] 2020-05-07 22:23
Hi,
I got the same error trying to run Poisson regression with an offset command. I have 700 observations made up of 5 groups. Two groups have many 0 values (but NOT the parallel offset variable). Any suggestions?

**Closed** 2020-05-15 20:15 UTC
Labels: bug
